# Generated by Django 4.2 on 2023-04-17 23:35

from django.conf import settings
from django.db import migrations, models
import game_app.models


class Migration(migrations.Migration):

    replaces = [('game_app', '0001_initial'), ('game_app', '0002_alter_game_player1_alter_game_player2_and_more'), ('game_app', '0003_game_current_turn_delete_move'), ('game_app', '0004_remove_game_current_turn_game_board_and_more'), ('game_app', '0005_alter_game_board'), ('game_app', '0006_alter_game_board')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default=game_app.models.GameState['waiting_room'], max_length=32)),
                ('winner', models.IntegerField(blank=True, null=True)),
                ('player1', models.CharField(max_length=32, null=True)),
                ('player2', models.CharField(max_length=32, null=True)),
                ('board', models.TextField(default='{\n  "rows": 7,\n  "columns": 7,\n  "max_moves": 49,\n  "board": [\n    [\n      "_",\n      "_",\n      "_",\n      "_",\n      "_",\n      "_",\n      "_"\n    ],\n    [\n      "_",\n      "_",\n      "_",\n      "_",\n      "_",\n      "_",\n      "_"\n    ],\n    [\n      "_",\n      "_",\n      "_",\n      "_",\n      "_",\n      "_",\n      "_"\n    ],\n    [\n      "_",\n      "_",\n      "_",\n      "_",\n      "_",\n      "_",\n      "_"\n    ],\n    [\n      "_",\n      "_",\n      "_",\n      "_",\n      "_",\n      "_",\n      "_"\n    ],\n    [\n      "_",\n      "_",\n      "_",\n      "_",\n      "_",\n      "_",\n      "_"\n    ],\n    [\n      "_",\n      "_",\n      "_",\n      "_",\n      "_",\n      "_",\n      "_"\n    ]\n  ],\n  "move_count": 0\n}')),
                ('board_move_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
